### ISSUE TITLE
Performance improvements

### ISSUE THREAD

**Issue by Scellow** [Leopotam/ecs-types#1]
I recently saw an article about the performance implication of C# struct equality

Implementing ``IEquatable<T>`` should be mendatory

https://www.reddit.com/r/programming/comments/8zi4sn/performance_implications_of_default_struct/

**Comment by Leopotam** [comment]
@Scellow well, i suggest to use special method for checking equality - `static bool Equals(ref A, ref B)`, because in standard C# compare behaviour both instances will be send by values. This method exists at all most classes at this repo.

**Comment by Leopotam** [comment]
@Scellow any objections?
