### ISSUE TITLE
bug: Int3.cs

### ISSUE THREAD

**Issue by XianWorld** [Leopotam/ecs-types#7]
line 152: res.Z = v.z;

        [MethodImpl (MethodImplOptions.AggressiveInlining)]
        public static implicit operator Int3 (in UnityEngine.Vector3Int v) {
            Int3 res;
            res.X = v.x;
            res.Y = v.y;
            res.Z = v.y;
            return res;
        }

**Comment by Leopotam** [comment]
@XianWorld fixed.
